classDiagram
class ForespørselFraHelsekontakt {
  +String innbyggerId
  +String tjeneste
  +String meldingInnhold
  +Vedlegg[] vedlegg
}
note for ForespørselFraHelsekontakt "Request from Health Contact"
