classDiagram
    class Request {
        +string[] fnrListe
        +Omraade omraade
    }

    class Omraade {
        <<enumeration>>
        Helsehjelp
        Ungdom
    }

    note for Omraade "Volven 7618: Helsehjelp=3, Ungdom=6"

    Request --> Omraade : omraade